
(() => {
 const nav=document.querySelector('.nav'), hamb=document.querySelector('.hamb'), prog=document.querySelector('.progress');
 const scroll=()=>{nav?.classList.toggle('scrolled',scrollY>18);if(prog){const m=document.documentElement.scrollHeight-innerHeight;prog.style.width=(m>0?scrollY/m*100:0)+'%'}};
 addEventListener('scroll',scroll,{passive:true});scroll();
 if(hamb&&nav){hamb.addEventListener('click',()=>{const o=nav.classList.toggle('open');hamb.setAttribute('aria-expanded',String(o));document.body.style.overflow=o?'hidden':''});addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');hamb.setAttribute('aria-expanded','false');document.body.style.overflow='';hamb.focus()}})}
 const cur=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.links a').forEach(a=>{if(a.getAttribute('href')===cur){a.classList.add('active');a.setAttribute('aria-current','page')}a.addEventListener('click',()=>{nav?.classList.remove('open');document.body.style.overflow='';hamb?.setAttribute('aria-expanded','false')})});
 if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}else document.querySelectorAll('.reveal').forEach(x=>x.classList.add('show'));
 const fleet=document.getElementById('fleet');if(fleet){const f=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)fleet.classList.add('visible')}),{threshold:.18});f.observe(fleet)}

 const form=document.getElementById('quoteForm');if(!form)return;
 const steps=[...form.querySelectorAll('.qstep')],prev=document.getElementById('prevStep'),next=document.getElementById('nextStep'),send=document.getElementById('sendQuote'),counter=document.getElementById('stepCounter'),title=document.getElementById('stepTitle'),bar=document.getElementById('progressBar'),status=document.getElementById('formStatus'),summary=document.getElementById('quoteSummary'),files=document.getElementById('quoteFiles'),filesInfo=document.getElementById('filesInfo');
 let step=1,started=Date.now(),last=0;
 const titles=['Quel type de travaux ?','Décrivez votre projet.','Où se trouve le chantier ?','Quel délai souhaitez-vous ?','Comment vous recontacter ?'];
 const serviceMap={'terrassement':'Terrassement','maconnerie':'Maçonnerie','facades-isolation':'Façades & isolation','amenagement-exterieur':'Aménagement extérieur'};
 const requested=new URLSearchParams(location.search).get('service');if(requested&&serviceMap[requested]){const r=form.querySelector(`input[name="service"][value="${serviceMap[requested]}"]`);if(r)r.checked=true}
 const val=n=>{const e=form.elements[n];return e instanceof RadioNodeList?e.value:(e?.value||'')};
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function valid(){const q=steps[step-1];let bad=null;[...q.querySelectorAll('[required]')].forEach(f=>{let ok=f.type==='radio'?!!q.querySelector(`input[name="${f.name}"]:checked`):f.type==='checkbox'?f.checked:(f.value.trim()!==''&&(!f.validity||f.validity.valid));if(!ok&&!bad)bad=f});if(bad){status.className='status err';status.textContent='Merci de compléter les champs nécessaires.';return false}status.textContent='';status.className='status';return true}
 function summ(){const rows=[['TRAVAUX',val('service')],['PROJET',val('type_projet')],['COMMUNE',[val('commune'),val('code_postal')].filter(Boolean).join(' · ')],['DÉLAI',val('delai')],['BUDGET',val('budget')||'Non défini']];summary.innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><b>${esc(v||'—')}</b></div>`).join('')}
 function update(){steps.forEach((s,i)=>{const a=i===step-1;s.classList.toggle('active',a);s.setAttribute('aria-hidden',String(!a))});counter.textContent=`ÉTAPE ${String(step).padStart(2,'0')} / 05`;title.textContent=titles[step-1];bar.style.width=step*20+'%';prev.style.visibility=step===1?'hidden':'visible';next.style.display=step===5?'none':'inline-flex';send.style.display=step===5?'inline-flex':'none';if(step===5)summ();requestAnimationFrame(()=>title.focus({preventScroll:true}));scrollTo({top:Math.max(0,form.getBoundingClientRect().top+scrollY-90),behavior:'smooth'})}
 next.addEventListener('click',()=>{if(valid()&&step<5){step++;update()}});prev.addEventListener('click',()=>{if(step>1){step--;status.textContent='';update()}});
 files?.addEventListener('change',()=>{const a=[...files.files],max=5*1024*1024,total=a.reduce((n,f)=>n+f.size,0);if(a.length>5||a.some(f=>f.size>max)||total>8*1024*1024){files.value='';filesInfo.textContent='Sélection refusée : 5 images max, 5 Mo chacune, 8 Mo au total.';status.className='status err';status.textContent='Réduisez le nombre ou la taille des photos.';return}filesInfo.textContent=a.length?a.map(f=>f.name).join(' · '):'5 Mo max par image · 8 Mo au total';status.textContent=''});
 form.addEventListener('submit',async e=>{e.preventDefault();if(!valid())return;if(form.elements._honey.value)return;if(Date.now()-started<2500){status.className='status err';status.textContent='Vérifiez votre demande puis réessayez.';return}if(Date.now()-last<60000){status.className='status err';status.textContent='Une demande vient déjà d’être envoyée. Attendez une minute.';return}last=Date.now();const fd=new FormData(form);fd.append('_subject',`Devis ORIS BAT PRO — ${val('service')} — ${val('commune')}`);fd.append('_template','table');[prev,next,send].forEach(b=>b.disabled=true);status.className='status';status.textContent='Envoi de votre demande...';let ok=false;for(let i=0;i<2&&!ok;i++){try{const r=await fetch('https://formsubmit.co/ajax/Orisbatpro@gmail.com',{method:'POST',body:fd,headers:{Accept:'application/json'}});ok=r.ok}catch(_){ }if(!ok&&i===0)await new Promise(r=>setTimeout(r,900))}
 if(ok){status.className='status ok';status.textContent='✅ Votre demande a bien été envoyée à ORIS BAT PRO.';form.reset();filesInfo.textContent='5 Mo max par image · 8 Mo au total';step=1;started=Date.now();update()}else{status.className='status err';status.innerHTML='❌ Envoi impossible pour le moment. Appelez le <a href="tel:0695238453">06 95 23 84 53</a> ou écrivez à <a href="mailto:Orisbatpro@gmail.com">Orisbatpro@gmail.com</a>.'}[prev,next,send].forEach(b=>b.disabled=false)});
 update();
})();
