
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function createViewer(root){
 const loading=root.querySelector('.viewer360-loading'),title=root.querySelector('[data-view-title]'),copy=root.querySelector('[data-view-copy]'),buttons=[...root.querySelectorAll('[data-view]')],beforeBtn=root.querySelector('[data-state="before"]'),afterBtn=root.querySelector('[data-state="after"]'),lightBtn=root.querySelector('[data-light]');
 const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b0d10);scene.fog=new THREE.FogExp2(0x0b0d10,.018);
 const camera=new THREE.PerspectiveCamera(42,1,.1,180);camera.position.set(13,9,16);
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;root.appendChild(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=31;controls.maxPolarAngle=Math.PI*.49;controls.target.set(0,2.1,0);
 const hemi=new THREE.HemisphereLight(0xffd3ad,0x1f2529,1.5);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffb268,4.1);sun.position.set(-12,18,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-24;sun.shadow.camera.right=24;sun.shadow.camera.top=24;sun.shadow.camera.bottom=-24;scene.add(sun);const fill=new THREE.DirectionalLight(0x8db8ff,1.25);fill.position.set(12,8,-12);scene.add(fill);
 const m={ground:new THREE.MeshStandardMaterial({color:0x514238,roughness:1}),soil:new THREE.MeshStandardMaterial({color:0x3b2b22,roughness:1}),gravel:new THREE.MeshStandardMaterial({color:0x82796f,roughness:.95}),concrete:new THREE.MeshStandardMaterial({color:0xb7afa5,roughness:.86}),wall:new THREE.MeshStandardMaterial({color:0xe0d8ce,roughness:.78}),dark:new THREE.MeshStandardMaterial({color:0x24282b,roughness:.72}),wood:new THREE.MeshStandardMaterial({color:0x77503b,roughness:.8}),glass:new THREE.MeshPhysicalMaterial({color:0x647c87,roughness:.12,transmission:.28,transparent:true,opacity:.78}),orange:new THREE.MeshStandardMaterial({color:0xf05b13,roughness:.58}),black:new THREE.MeshStandardMaterial({color:0x17191b,roughness:.7}),tire:new THREE.MeshStandardMaterial({color:0x171819,roughness:1}),green:new THREE.MeshStandardMaterial({color:0x435240,roughness:1}),paver:new THREE.MeshStandardMaterial({color:0x9b9389,roughness:.95})};
 const before=new THREE.Group(),after=new THREE.Group(),always=new THREE.Group();scene.add(before,after,always);
 function mesh(g,mat,pos=[0,0,0],rot=[0,0,0],parent=always,cast=true,receive=true){const o=new THREE.Mesh(g,mat);o.position.set(...pos);o.rotation.set(...rot);o.castShadow=cast;o.receiveShadow=receive;parent.add(o);return o}function box(w,h,d,mat,pos,rot=[0,0,0],parent=always){return mesh(new THREE.BoxGeometry(w,h,d),mat,pos,rot,parent)}function cyl(r,h,mat,pos,rot=[0,0,0],parent=always,seg=24){return mesh(new THREE.CylinderGeometry(r,r,h,seg),mat,pos,rot,parent)}
 box(34,.5,26,m.ground,[0,-.3,0],[0,0,0],always,false,true);box(13,.12,12,m.soil,[-6,.02,2],[0,0,0],before,false,true);box(13,.14,12,m.gravel,[-6,.03,2],[0,0,0],after,false,true);box(8,.12,12,m.soil,[6,.02,1],[0,0,0],before,false,true);box(8,.14,12,m.paver,[6,.04,1],[0,0,0],after,false,true);
 const house=new THREE.Group();always.add(house);box(12,4.3,7,m.wall,[2,2.1,-4],[0,0,0],house);box(5.4,2.1,.18,m.dark,[4.2,1.25,-.42],[0,0,0],house);box(2.4,2.3,.12,m.glass,[-1.5,1.6,-.40],[0,0,0],house);box(1.15,2.25,.16,m.dark,[.55,1.2,-.39],[0,0,0],house);box(2.4,.22,.7,m.dark,[.55,2.55,-.45],[0,0,0],house);box(12,.35,7.35,m.dark,[2,4.45,-4],[0,0,0],house);box(3,.06,.9,m.wood,[-2.3,4.28,-.45],[0,0,0],house);box(5.6,2.4,6.1,m.wall,[-.6,5.65,-4],[0,0,0],house);box(2.1,1.45,.12,m.glass,[-2,5.8,-.88],[0,0,0],house);box(2.1,1.45,.12,m.glass,[.6,5.8,-.88],[0,0,0],house);box(5.9,.3,6.3,m.dark,[-.6,7,-4],[0,0,0],house);
 for(let i=0;i<5;i++)box(4.8,.6,.72,m.concrete,[-1.7+i*.02,.27+i*.25,1.5+i*.62],[0,0,0],after);box(8.2,.9,.75,m.concrete,[-2.5,.4,4.2],[0,0,0],after);box(5.8,.9,.75,m.concrete,[-4.3,.4,1.5],[0,0,0],after);box(8,.8,1.4,m.soil,[-2.7,.2,4.2],[0,0,.08],before);box(5.5,.7,1.2,m.soil,[-4.1,.15,1.5],[0,0,-.07],before);
 function tree(x,z,s=1){cyl(.16,2.2*s,m.wood,[x,1.05*s,z],[0,0,0],after,18);mesh(new THREE.IcosahedronGeometry(1.1*s,2),m.green,[x,2.35*s,z],[0,0,0],after)}tree(-5,-3,.8);tree(-7,5,.75);tree(9,-4,.72);[[-3,5.2],[-1.6,5.4],[1,5.2],[8,4.7]].forEach(([x,z])=>mesh(new THREE.SphereGeometry(.55,18,12),m.green,[x,.55,z],[0,0,0],after));
 const ex=new THREE.Group();ex.position.set(-7,.35,1.8);ex.rotation.y=.45;always.add(ex);box(4.1,.55,1,m.tire,[0,.38,.72],[0,0,0],ex);box(4.1,.55,1,m.tire,[0,.38,-.72],[0,0,0],ex);box(3.2,.26,2,m.black,[0,.83,0],[0,0,0],ex);box(2.6,.95,1.8,m.orange,[.15,1.34,0],[0,0,0],ex);box(1.35,1.75,1.6,m.dark,[.45,2.55,.05],[0,0,0],ex);box(1.08,1.28,.06,m.glass,[.46,2.68,.87],[0,0,0],ex);const boomPivot=new THREE.Group();boomPivot.position.set(1.15,2.05,0);ex.add(boomPivot);box(3.65,.35,.5,m.orange,[1.65,.75,0],[0,0,-.38],boomPivot);const armPivot=new THREE.Group();armPivot.position.set(3.22,-.02,0);boomPivot.add(armPivot);box(2.75,.31,.46,m.orange,[1.18,-.65,0],[0,0,.55],armPivot);box(1.05,.9,.7,m.black,[2.55,-1.36,0],[0,0,-.18],armPivot);cyl(.09,2.2,m.concrete,[1.2,.62,.38],[0,0,.98],boomPivot,14);
 function cone(x,z){mesh(new THREE.ConeGeometry(.23,.7,18),m.orange,[x,.35,z]);cyl(.34,.06,m.black,[x,.03,z])}cone(-1,7);cone(1,7.5);cone(4,6);
 function state(s){before.visible=s==='before';after.visible=s==='after';beforeBtn?.classList.toggle('active',s==='before');afterBtn?.classList.toggle('active',s==='after');if(title)title.textContent=s==='before'?'Terrain brut':'Projet aménagé';if(copy)copy.textContent=s==='before'?'Visualisez le terrain avant la préparation des niveaux, murets et accès.':'Visualisez un concept après préparation du terrain, murets, marches, accès et végétalisation.'}state('after');beforeBtn?.addEventListener('click',()=>state('before'));afterBtn?.addEventListener('click',()=>state('after'));
 const views={global:{p:[13,9,16],t:[0,2.1,0],h:'Vue globale',c:'Faites glisser la scène pour tourner autour de la maison à 360°. Pincez ou utilisez la molette pour zoomer.'},terrassement:{p:[-12,5,12],t:[-4,.8,2],h:'Terrassement',c:'Vue sur la mini-pelle, le terrain, les niveaux et la préparation des accès.'},maconnerie:{p:[6,6,13],t:[-1,1.1,2.6],h:'Maçonnerie',c:'Vue sur les murets, marches, seuils et ouvrages qui structurent les abords.'},facade:{p:[11,7,7],t:[2,3,-3.5],h:'Façade',c:'Vue sur la maison, les ouvertures, le soubassement et la façade.'},acces:{p:[13,4,13],t:[5,.5,1],h:'Accès & cour',c:'Vue sur la circulation véhicule, le stationnement et les niveaux de la cour.'}};let target={p:new THREE.Vector3(...views.global.p),t:new THREE.Vector3(...views.global.t)},moving=false;
 function go(n){const v=views[n]||views.global;target={p:new THREE.Vector3(...v.p),t:new THREE.Vector3(...v.t)};moving=true;buttons.forEach(b=>b.classList.toggle('active',b.dataset.view===n));if(title)title.textContent=v.h;if(copy)copy.textContent=v.c}buttons.forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));go('global');let dusk=true;lightBtn?.addEventListener('click',()=>{dusk=!dusk;scene.background.set(dusk?0x0b0d10:0xc7d4df);scene.fog.color.set(dusk?0x0b0d10:0xc7d4df);hemi.intensity=dusk?1.5:2.2;sun.intensity=dusk?4.1:3.1;renderer.toneMappingExposure=dusk?1.15:1;lightBtn.textContent=dusk?'Mode jour':'Mode crépuscule'});
 function resize(){const r=root.getBoundingClientRect(),w=Math.max(320,r.width),h=Math.max(520,r.height);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}new ResizeObserver(resize).observe(root);resize();let time=0;function loop(){time+=.012;if(!reduced){boomPivot.rotation.z=-.03+Math.sin(time*.55)*.018;armPivot.rotation.z=Math.sin(time*.62)*.025}if(moving){camera.position.lerp(target.p,.055);controls.target.lerp(target.t,.055);if(camera.position.distanceTo(target.p)<.04&&controls.target.distanceTo(target.t)<.04)moving=false}controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();if(loading)loading.style.display='none';renderer.domElement.setAttribute('aria-label','Scène 3D interactive ORIS BAT PRO, rotative à 360 degrés.');
}
const viewers=[...document.querySelectorAll('[data-viewer360]')];if(viewers.length){const init=v=>{if(v.dataset.ready)return;v.dataset.ready='1';try{createViewer(v)}catch(e){console.warn(e);const s=v.querySelector('.viewer360-loading span');if(s)s.textContent='Mode photo activé'}};if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){init(e.target);io.unobserve(e.target)}}),{rootMargin:'450px'});viewers.forEach(v=>io.observe(v))}else viewers.forEach(init)}
